services:
    setup_inicial_app:
        build: .
        container_name: setup_inicial_app
        image: setup_inicial:latest
        ports:
            - 3000:3000
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - ./package.json:/app/package.json
            - /app/node_modules
